"""EMA Pullback State Machine Strategy.

Inspired by the 4-phase pullback strategy (backtested: Sharpe 0.89, WR 55.43%,
Max DD 5.81%, +44.75% over 5 years on XAUUSD).

Entry logic:
  1. SCANNING: Wait for EMA(8) crossover of EMA(21) with H1 regime confirmation
  2. ARMED: Wait for 1-3 counter-trend pullback candles
  3. WINDOW_OPEN: Set breakout level, monitor for 2 candles
  4. ENTRY: Execute on breakout confirmation

Exit logic:
  - SL: 2x ATR(14) from entry
  - TP: 3x ATR(14) from entry (conservative; can increase later)
  - Trailing stop handled by PositionMonitor (Phase 2)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

import pandas as pd
import pandas_ta as ta

from src.config.schema import EmaPullbackConfig

logger = logging.getLogger(__name__)


class State(str, Enum):
    SCANNING = "SCANNING"
    ARMED = "ARMED"
    WINDOW_OPEN = "WINDOW_OPEN"


@dataclass
class SymbolState:
    """Per-symbol state machine tracking."""

    state: State = State.SCANNING
    direction: str = ""  # "BUY" or "SELL"
    armed_at: datetime | None = None
    pullback_count: int = 0
    breakout_level: float = 0.0
    window_candles: int = 0
    last_crossover_bar: int = -1


@dataclass
class StrategySignal:
    """Signal generated by the strategy."""

    symbol: str
    action: str  # "BUY" or "SELL"
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float
    reason: str


class EmaPullbackStrategy:
    """4-phase state machine: SCANNING → ARMED → WINDOW_OPEN → ENTRY."""

    def __init__(self, config: EmaPullbackConfig) -> None:
        self._config = config
        self._states: dict[str, SymbolState] = {}

    def _get_state(self, symbol: str) -> SymbolState:
        if symbol not in self._states:
            self._states[symbol] = SymbolState()
        return self._states[symbol]

    async def scan(
        self,
        symbol: str,
        m15_bars: pd.DataFrame,
        h1_regime_is_trending_up: bool,
        h1_regime_is_trending_down: bool,
        h1_regime_is_choppy: bool,
    ) -> StrategySignal | None:
        """Run one scan cycle for a symbol. Returns a signal or None.

        Args:
            symbol: Instrument symbol (e.g., "XAUUSD")
            m15_bars: M15 OHLCV DataFrame (at least 60 bars)
            h1_regime_is_trending_up: True if H1 regime is bullish
            h1_regime_is_trending_down: True if H1 regime is bearish
            h1_regime_is_choppy: True if H1 regime is choppy (skip)
        """
        if h1_regime_is_choppy:
            # Reset state in choppy markets
            self._states.pop(symbol, None)
            return None

        if m15_bars is None or len(m15_bars) < 60:
            return None

        cfg = self._config
        st = self._get_state(symbol)

        # Calculate indicators
        fast_ema = ta.ema(m15_bars["close"], length=cfg.fast_ema)
        slow_ema = ta.ema(m15_bars["close"], length=cfg.slow_ema)
        atr = ta.atr(m15_bars["high"], m15_bars["low"], m15_bars["close"], length=14)

        if fast_ema is None or slow_ema is None or atr is None:
            return None

        current_fast = float(fast_ema.iloc[-1])
        current_slow = float(slow_ema.iloc[-1])
        prev_fast = float(fast_ema.iloc[-2])
        prev_slow = float(slow_ema.iloc[-2])
        current_atr = float(atr.iloc[-1])
        current_close = float(m15_bars["close"].iloc[-1])
        current_high = float(m15_bars["high"].iloc[-1])
        current_low = float(m15_bars["low"].iloc[-1])
        prev_close = float(m15_bars["close"].iloc[-2])

        if current_atr <= 0:
            return None

        # ── STATE: SCANNING ──
        if st.state == State.SCANNING:
            # Detect EMA crossover
            bullish_cross = prev_fast <= prev_slow and current_fast > current_slow
            bearish_cross = prev_fast >= prev_slow and current_fast < current_slow

            if bullish_cross and h1_regime_is_trending_up:
                st.state = State.ARMED
                st.direction = "BUY"
                st.armed_at = datetime.utcnow()
                st.pullback_count = 0
                logger.info(
                    "EMA Pullback [%s]: SCANNING → ARMED (bullish cross, regime=UP)",
                    symbol,
                )

            elif bearish_cross and h1_regime_is_trending_down:
                st.state = State.ARMED
                st.direction = "SELL"
                st.armed_at = datetime.utcnow()
                st.pullback_count = 0
                logger.info(
                    "EMA Pullback [%s]: SCANNING → ARMED (bearish cross, regime=DOWN)",
                    symbol,
                )

            return None

        # ── STATE: ARMED (waiting for pullback) ──
        if st.state == State.ARMED:
            # Check for pullback candle (closes against the direction)
            is_pullback = (
                (st.direction == "BUY" and current_close < prev_close)
                or (st.direction == "SELL" and current_close > prev_close)
            )

            if is_pullback:
                st.pullback_count += 1
                logger.debug(
                    "EMA Pullback [%s]: pullback candle %d/%d",
                    symbol, st.pullback_count, cfg.pullback_max_candles,
                )

                if st.pullback_count >= 1:
                    # Set breakout level and open window
                    if st.direction == "BUY":
                        st.breakout_level = current_high
                    else:
                        st.breakout_level = current_low

                    st.state = State.WINDOW_OPEN
                    st.window_candles = 0
                    logger.info(
                        "EMA Pullback [%s]: ARMED → WINDOW_OPEN "
                        "(pullback=%d, breakout=%.5f)",
                        symbol, st.pullback_count, st.breakout_level,
                    )

            # Timeout: too many candles without pullback
            elif st.pullback_count == 0:
                # Check if EMA cross is still valid
                if st.direction == "BUY" and current_fast < current_slow:
                    st.state = State.SCANNING
                    logger.debug("EMA Pullback [%s]: ARMED → SCANNING (cross invalidated)", symbol)
                elif st.direction == "SELL" and current_fast > current_slow:
                    st.state = State.SCANNING
                    logger.debug("EMA Pullback [%s]: ARMED → SCANNING (cross invalidated)", symbol)

            return None

        # ── STATE: WINDOW_OPEN (waiting for breakout) ──
        if st.state == State.WINDOW_OPEN:
            st.window_candles += 1

            breakout = False
            if st.direction == "BUY" and current_close > st.breakout_level:
                breakout = True
            elif st.direction == "SELL" and current_close < st.breakout_level:
                breakout = True

            if breakout:
                # ENTRY — generate signal
                entry = current_close
                sl_distance = current_atr * cfg.atr_sl_multiplier
                tp_distance = current_atr * cfg.atr_tp_multiplier

                if st.direction == "BUY":
                    sl = entry - sl_distance
                    tp = entry + tp_distance
                else:
                    sl = entry + sl_distance
                    tp = entry - tp_distance

                # Reset state
                st.state = State.SCANNING
                st.pullback_count = 0

                logger.info(
                    "EMA Pullback [%s]: ENTRY → %s @ %.5f SL=%.5f TP=%.5f "
                    "(ATR=%.5f, pullback confirmed)",
                    symbol, st.direction, entry, sl, tp, current_atr,
                )

                return StrategySignal(
                    symbol=symbol,
                    action=st.direction,
                    entry_price=entry,
                    stop_loss=sl,
                    take_profit=tp,
                    confidence=0.75,
                    reason="EMA pullback breakout (regime-confirmed)",
                )

            # Window expired
            if st.window_candles >= cfg.entry_window_candles:
                st.state = State.SCANNING
                st.pullback_count = 0
                logger.debug(
                    "EMA Pullback [%s]: WINDOW_OPEN → SCANNING (window expired)",
                    symbol,
                )

            return None

        return None
