"""London Session Breakout Strategy.

Trades the breakout of the Asian session range at London open.
Direction correct ~65-70% of the time historically for Gold.

Rules:
  1. Mark Asian range (00:00-07:00 UTC high/low) from M15 bars
  2. At London open (07:00+ UTC), wait for breakout above/below range
  3. Breakout = close above Asian high + buffer (longs) or below low - buffer (shorts)
  4. SL = opposite side of Asian range
  5. TP = 1.5x the Asian range width
  6. One trade per day per symbol
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone

import pandas as pd

from src.config.schema import LondonBreakoutConfig

logger = logging.getLogger(__name__)


@dataclass
class AsianRange:
    """Tracked Asian session range for the day."""

    date: str  # "YYYY-MM-DD"
    high: float
    low: float
    range_pips: float
    traded_today: bool = False


@dataclass
class StrategySignal:
    """Signal generated by the strategy."""

    symbol: str
    action: str
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float
    reason: str


class LondonBreakoutStrategy:
    """Asian range breakout at London open."""

    def __init__(self, config: LondonBreakoutConfig) -> None:
        self._config = config
        self._ranges: dict[str, AsianRange] = {}  # symbol → today's range

    async def scan(
        self,
        symbol: str,
        m15_bars: pd.DataFrame,
        point_size: float,
        regime_is_choppy: bool,
        regime_is_ranging: bool,
        as_of: datetime | None = None,
    ) -> StrategySignal | None:
        """Run one scan cycle. Returns a signal or None.

        Args:
            symbol: Instrument symbol
            m15_bars: M15 OHLCV DataFrame with datetime index or 'time' column
            point_size: Symbol point size for pip calculation
            regime_is_choppy: Skip if True
            regime_is_ranging: Skip if True (breakout needs trend)
            as_of: Override current time (for backtesting). None = use real time.
        """
        if regime_is_choppy or regime_is_ranging:
            return None

        if m15_bars is None or len(m15_bars) < 30:
            return None

        now = as_of or datetime.now(timezone.utc)
        today_str = now.strftime("%Y-%m-%d")
        current_hour = now.hour

        cfg = self._config

        # Only active during London session (07:00-12:00 UTC)
        if current_hour < cfg.asian_end_hour or current_hour >= 12:
            return None

        # Check if already traded today
        existing = self._ranges.get(symbol)
        if existing and existing.date == today_str and existing.traded_today:
            return None

        # Mark Asian range if not done today
        if existing is None or existing.date != today_str:
            asian_range = self._calculate_asian_range(
                m15_bars, cfg.asian_start_hour, cfg.asian_end_hour, now
            )
            if asian_range is None:
                logger.info("London Breakout [%s]: no Asian range found for %s", symbol, today_str)
                return None

            range_width = asian_range[0] - asian_range[1]
            if range_width <= 0:
                return None

            self._ranges[symbol] = AsianRange(
                date=today_str,
                high=asian_range[0],
                low=asian_range[1],
                range_pips=range_width / point_size if point_size > 0 else range_width,
            )
            logger.info(
                "London Breakout [%s]: Asian range high=%.5f low=%.5f (%.1f pips)",
                symbol, asian_range[0], asian_range[1],
                self._ranges[symbol].range_pips,
            )

            # Stale breakout detection: if price already above/below range,
            # the breakout happened before we started — skip it
            first_check_close = float(m15_bars["close"].iloc[-1])
            buffer_check = cfg.breakout_buffer_pips * point_size
            if first_check_close > asian_range[0] + buffer_check or first_check_close < asian_range[1] - buffer_check:
                self._ranges[symbol].traded_today = True
                logger.info(
                    "London Breakout [%s]: stale breakout detected (price %.2f already outside range), skipping",
                    symbol, first_check_close,
                )
                return None

        ar = self._ranges[symbol]
        buffer = cfg.breakout_buffer_pips * point_size

        # Check for breakout using latest candle close
        current_close = float(m15_bars["close"].iloc[-1])

        # Bullish breakout
        if current_close > ar.high + buffer:
            ar.traded_today = True
            sl = ar.low
            range_width = ar.high - ar.low
            tp = current_close + range_width * cfg.tp_multiplier

            logger.info(
                "London Breakout [%s]: BUY breakout @ %.5f "
                "(Asian high=%.5f, SL=%.5f, TP=%.5f)",
                symbol, current_close, ar.high, sl, tp,
            )

            return StrategySignal(
                symbol=symbol,
                action="BUY",
                entry_price=current_close,
                stop_loss=sl,
                take_profit=tp,
                confidence=0.70,
                reason=f"London breakout above Asian range ({ar.range_pips:.0f} pip range)",
            )

        # Bearish breakout
        if current_close < ar.low - buffer:
            ar.traded_today = True
            sl = ar.high
            range_width = ar.high - ar.low
            tp = current_close - range_width * cfg.tp_multiplier

            logger.info(
                "London Breakout [%s]: SELL breakout @ %.5f "
                "(Asian low=%.5f, SL=%.5f, TP=%.5f)",
                symbol, current_close, ar.low, sl, tp,
            )

            return StrategySignal(
                symbol=symbol,
                action="SELL",
                entry_price=current_close,
                stop_loss=sl,
                take_profit=tp,
                confidence=0.70,
                reason=f"London breakout below Asian range ({ar.range_pips:.0f} pip range)",
            )

        return None

    def _calculate_asian_range(
        self,
        bars: pd.DataFrame,
        start_hour: int,
        end_hour: int,
        as_of: datetime | None = None,
    ) -> tuple[float, float] | None:
        """Calculate the high/low of the Asian session from M15 bars.

        Returns (high, low) or None if insufficient data.
        """
        # Filter bars to today's Asian session
        now = as_of or datetime.now(timezone.utc)
        today = now.date()

        asian_bars = []
        for i in range(len(bars)):
            bar_time = None
            # Use DatetimeIndex first (most reliable from MT5 client)
            if bars.index.dtype.kind == "M":
                bar_time = bars.index[i]
            elif "time" in bars.columns:
                val = bars["time"].iloc[i]
                # Handle unix seconds (int/float) vs datetime
                if isinstance(val, (int, float)):
                    bar_time = pd.Timestamp(val, unit="s", tz="UTC")
                else:
                    bar_time = pd.Timestamp(val)

            if bar_time is None:
                continue

            if hasattr(bar_time, "tz_localize") and bar_time.tzinfo is None:
                bar_time = bar_time.tz_localize("UTC")

            if (bar_time.date() == today
                    and start_hour <= bar_time.hour < end_hour):
                asian_bars.append(i)

        if len(asian_bars) < 4:  # Need at least 4 M15 bars (1 hour of data)
            return None

        asian_high = float(bars["high"].iloc[asian_bars].max())
        asian_low = float(bars["low"].iloc[asian_bars].min())

        return asian_high, asian_low
