"""NY Session Strategies — Range Breakout + Momentum Continuation.

Two complementary strategies for the New York session (13:00-22:00 UTC):

Component A: NY Range Breakout
  - Marks the 13:00-14:00 UTC range (first hour of NY session)
  - Trades breakouts during 14:00-18:00 UTC
  - Works in ALL regimes except RANGING
  - Same proven pattern as London Breakout

Component B: NY Momentum Continuation
  - RSI(14) cross + MACD(12,26,9) confirmation + EMA(21) filter
  - Catches continuation moves after initial breakout
  - Works in ALL regimes including CHOPPY (detects shift to directional)
  - Active 15:00-21:00 UTC
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone

import pandas as pd
import pandas_ta as ta

logger = logging.getLogger(__name__)


@dataclass
class StrategySignal:
    """Signal generated by the strategy."""
    symbol: str
    action: str
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float
    reason: str


@dataclass
class NyRange:
    """Tracked NY session range for the day."""
    date: str
    high: float
    low: float
    range_width: float
    breakout_traded: bool = False


class NyRangeBreakoutStrategy:
    """NY session range breakout — marks 13:00-14:00 range, trades breakout."""

    def __init__(
        self,
        breakout_buffer_pips: float = 3.0,
        tp_multiplier: float = 2.0,
        max_trades_per_day: int = 1,
    ) -> None:
        self._buffer_pips = breakout_buffer_pips
        self._tp_mult = tp_multiplier
        self._max_trades = max_trades_per_day
        self._ranges: dict[str, NyRange] = {}

    async def scan(
        self,
        symbol: str,
        m15_bars: pd.DataFrame,
        point_size: float,
        regime_is_ranging: bool,
        as_of: datetime | None = None,
    ) -> StrategySignal | None:
        """Scan for NY range breakout."""
        if regime_is_ranging:
            return None

        if m15_bars is None or len(m15_bars) < 30:
            return None

        now = as_of or datetime.now(timezone.utc)
        today_str = now.strftime("%Y-%m-%d")
        hour = now.hour

        # Only active 14:00-18:00 UTC (after range established)
        if hour < 14 or hour >= 18:
            return None

        # Check daily limit
        existing = self._ranges.get(symbol)
        if existing and existing.date == today_str and existing.breakout_traded:
            return None

        # Build NY range (13:00-14:00 UTC) if not done today
        if existing is None or existing.date != today_str:
            ny_range = self._calculate_ny_range(m15_bars, now)
            if ny_range is None:
                return None
            self._ranges[symbol] = ny_range
            logger.info(
                "NY Range [%s]: high=%.5f low=%.5f (width=%.5f)",
                symbol, ny_range.high, ny_range.low, ny_range.range_width,
            )

        nr = self._ranges[symbol]
        if nr.range_width <= 0:
            return None

        buffer = self._buffer_pips * point_size
        current_close = float(m15_bars["close"].iloc[-1])

        # Bullish breakout
        if current_close > nr.high + buffer:
            nr.breakout_traded = True
            sl = nr.low
            tp = current_close + nr.range_width * self._tp_mult
            logger.info(
                "NY Range Breakout [%s]: BUY @ %.5f (range high=%.5f)",
                symbol, current_close, nr.high,
            )
            return StrategySignal(
                symbol=symbol, action="BUY", entry_price=current_close,
                stop_loss=sl, take_profit=tp, confidence=0.70,
                reason=f"NY range breakout above {nr.high:.2f}",
            )

        # Bearish breakout
        if current_close < nr.low - buffer:
            nr.breakout_traded = True
            sl = nr.high
            tp = current_close - nr.range_width * self._tp_mult
            logger.info(
                "NY Range Breakout [%s]: SELL @ %.5f (range low=%.5f)",
                symbol, current_close, nr.low,
            )
            return StrategySignal(
                symbol=symbol, action="SELL", entry_price=current_close,
                stop_loss=sl, take_profit=tp, confidence=0.70,
                reason=f"NY range breakout below {nr.low:.2f}",
            )

        return None

    def _calculate_ny_range(
        self, bars: pd.DataFrame, now: datetime,
    ) -> NyRange | None:
        """Calculate 13:00-14:00 UTC range from M15 bars."""
        today = now.date()
        today_str = now.strftime("%Y-%m-%d")
        ny_bars = []

        for i in range(len(bars)):
            bar_time = None
            if "time" in bars.columns:
                bar_time = pd.Timestamp(bars["time"].iloc[i])
            elif bars.index.dtype.kind == "M":
                bar_time = bars.index[i]
            if bar_time is None:
                continue
            if hasattr(bar_time, "tz_localize") and bar_time.tzinfo is None:
                bar_time = bar_time.tz_localize("UTC")
            if bar_time.date() == today and 13 <= bar_time.hour < 14:
                ny_bars.append(i)

        if len(ny_bars) < 2:
            return None

        high = float(bars["high"].iloc[ny_bars].max())
        low = float(bars["low"].iloc[ny_bars].min())
        return NyRange(date=today_str, high=high, low=low, range_width=high - low)


class NyMomentumStrategy:
    """NY momentum continuation — RSI cross + MACD + EMA filter."""

    def __init__(self, max_trades_per_day: int = 1) -> None:
        self._max_trades = max_trades_per_day
        self._daily_trades: dict[str, tuple[str, int]] = {}  # symbol → (date, count)

    async def scan(
        self,
        symbol: str,
        m15_bars: pd.DataFrame,
        regime_is_ranging: bool,
        as_of: datetime | None = None,
    ) -> StrategySignal | None:
        """Scan for RSI+MACD momentum shift."""
        if regime_is_ranging:
            return None

        if m15_bars is None or len(m15_bars) < 30:
            return None

        now = as_of or datetime.now(timezone.utc)
        today_str = now.strftime("%Y-%m-%d")
        hour = now.hour

        # Active 15:00-21:00 UTC
        if hour < 15 or hour >= 21:
            return None

        # Daily limit
        entry = self._daily_trades.get(symbol, ("", 0))
        if entry[0] == today_str and entry[1] >= self._max_trades:
            return None

        close = m15_bars["close"]
        high = m15_bars["high"]
        low = m15_bars["low"]

        # Calculate indicators
        rsi = ta.rsi(close, length=14)
        macd_result = ta.macd(close, fast=12, slow=26, signal=9)
        ema21 = ta.ema(close, length=21)
        atr = ta.atr(high, low, close, length=14)

        if rsi is None or macd_result is None or ema21 is None or atr is None:
            return None

        curr_rsi = float(rsi.iloc[-1])
        prev_rsi = float(rsi.iloc[-2])
        curr_macd_hist = float(macd_result.iloc[-1, 2])  # histogram column
        curr_close = float(close.iloc[-1])
        curr_ema21 = float(ema21.iloc[-1])
        curr_atr = float(atr.iloc[-1])

        if curr_atr <= 0:
            return None

        sl_distance = curr_atr * 3.5
        tp_distance = curr_atr * 10.0

        # BUY: RSI crosses above 50 + MACD histogram positive + price > EMA21
        if prev_rsi < 50 and curr_rsi >= 50 and curr_macd_hist > 0 and curr_close > curr_ema21:
            sl = curr_close - sl_distance
            tp = curr_close + tp_distance
            self._daily_trades[symbol] = (today_str, entry[1] + 1 if entry[0] == today_str else 1)
            logger.info(
                "NY Momentum [%s]: BUY @ %.5f (RSI=%.1f, MACD_hist=%.5f)",
                symbol, curr_close, curr_rsi, curr_macd_hist,
            )
            return StrategySignal(
                symbol=symbol, action="BUY", entry_price=curr_close,
                stop_loss=sl, take_profit=tp, confidence=0.60,
                reason=f"NY momentum BUY (RSI {curr_rsi:.0f}, MACD+)",
            )

        # SELL: RSI crosses below 50 + MACD histogram negative + price < EMA21
        if prev_rsi > 50 and curr_rsi <= 50 and curr_macd_hist < 0 and curr_close < curr_ema21:
            sl = curr_close + sl_distance
            tp = curr_close - tp_distance
            self._daily_trades[symbol] = (today_str, entry[1] + 1 if entry[0] == today_str else 1)
            logger.info(
                "NY Momentum [%s]: SELL @ %.5f (RSI=%.1f, MACD_hist=%.5f)",
                symbol, curr_close, curr_rsi, curr_macd_hist,
            )
            return StrategySignal(
                symbol=symbol, action="SELL", entry_price=curr_close,
                stop_loss=sl, take_profit=tp, confidence=0.60,
                reason=f"NY momentum SELL (RSI {curr_rsi:.0f}, MACD-)",
            )

        return None
